import requests
import os
from datetime import datetime

ORG_NAME = "MakerHub-24-7"
OUTPUT_DIR = "reports"

os.makedirs(OUTPUT_DIR, exist_ok=True)

print("MakerHub Intelligence System Running")

repos_url = f"https://api.github.com/orgs/{ORG_NAME}/repos"
repos = requests.get(repos_url).json()

repo_count = len(repos)
total_stars = 0
total_forks = 0

repo_lines = []

for repo in repos:
    name = repo["name"]
    stars = repo["stargazers_count"]
    forks = repo["forks_count"]
    updated = repo["updated_at"]

    total_stars += stars
    total_forks += forks

    repo_lines.append(f"| {name} | {stars} | {forks} | {updated} |")

report = f"""
# MakerHub Organization Intelligence Report

Generated: {datetime.utcnow()}

## Organization Overview

Repositories: {repo_count}  
Total Stars: {total_stars}  
Total Forks: {total_forks}

---

## Repository Activity

| Repository | Stars | Forks | Last Updated |
|-----------|------|------|-------------|
{chr(10).join(repo_lines)}

---

## Research System Notes

This report was automatically generated by the MakerHub AI system.

Data source: GitHub Organization API.
"""

output_file = os.path.join(OUTPUT_DIR, "organization_report.md")

with open(output_file, "w") as f:
    f.write(report)

print("Report generated:", output_file)
